### ISSUE TITLE
2.3.x getting started code example issues

### ISSUE THREAD

**Issue by kochen** [patchlevel/event-sourcing-bundle#158]
Great work on this library!

There are several issues with the  code example provided in the docs.

Besides the semantic issues, the example will not work with the default installation, because the table `hotel` will conflict between the projection and the event store.
This would require either, change the projection table name, or set the project to use a single event store (I'd say easier to start with anyway, but a bit less out-of-the-box).

**Comment by kochen** [comment]
@DanielBadura what shall we do with the Store type?

**Comment by DanielBadura** [comment]
I just read it now, sorry.

I would say we update the projection table name in the example, it is less invasive. Also, multitable store will be removed in `3.0`.

**Comment by kochen** [comment]
> I just read it now, sorry.

No worries.

> I would say we update the projection table name in the example, it is less invasive. Also, multitable store will be removed in `3.0`.

What? Why?!
also: it's not what the documentation of 3.x says (updated several years ago)...

**Comment by DavidBadura** [comment]
Hey, sorry for the confusion.


**First about the MultiTable Store:**

It's really difficult to implement a "MutliTable" store. The main challenge here was that the events always had to be in the correct order, even if they were reloaded from the DB across all aggregates. This is important for the pipeline as well as for the projectionist (async projections). We solved this by having a table for each aggregate, but also a meta table that is filled at the same time. Every event is always written in two tables. When you read, the “magic” happens. We fetch across all aggregates and the meta table. We always work with a cursor so as not to load all the data into memory. First we load the first row from the meta table to know which table we have to read for the first event. Then we load the corresponding next line in the aggregate table, where the payload from the event can also be found. And this happens for every event in the meta table. At the same time there are checks to make sure that the tables are in sync.

In summary, we always write to multiple tables and have to read multiple tables to build a stream.

What do we gain? Nothing, except developer experience when looking at the data in the database.
And for this, we have created some commands and are considering adding a UI (#130).

What price do we pay? Negative effect on the read/write speed. A good index is just as fast as a separate table. More memory consumption because some data is duplicated. Complicated procedure and potential errors. And above all, why we threw out this feature: It's difficult to filter without actually duplicating the data 100%.

That's why we decided to drop the Multi Table Store because we no longer use it ourselves.

Can you think of a reason to keep the Multi Table Store?


**Regarding the documentation in the bundle:**

Yes, it is outdated for 3.0 and not yet updated, but the version is not released yet. We work primarily library-centered and the bundle is currently being updated enough so that we can use it in our own project. Before we release the bundle to the latest version, we will deprecate things, write upgrade documentation and update the documentation.
